### PR TITLE
Added infer.NET local libraries (fixes broken references). Added some code doc. Added explicit names to a co...

### PR DESCRIPTION
**Pull request by tdiethe**
...uple of infer.net variables (for showing in factor graph). Moved engine initialisation to after definition.

### CODE REVIEW

**Comment by oliparson** [comment]
Hi Tom, thanks for these changes. I intentionally didn't include the Infer.NET dlls in the repository as I assumed I didn't have the rights to distribute them. Is including them the correct thing to do?

**Comment by tdiethe** [comment]
Good point! I feel rather sheepish now ...

Infer.NET is now up on Nuget (officially this time!) so perhaps it can be
set up to use that instead? I'll look into that. The license actually
agrees with you (for the compiler - there's nothing about the runtime)  ...

You may not distribute the compiler binary for this Software or any
derivative works in
any form. For purposes of clarity, a derivative work does not include any
code
generated as a result of running the compiler binary in its intended form
and noncommercial
purpose (“Generated Code”).

http://research.microsoft.com/en-us/um/cambridge/projects/infernet/InferNetLicense_2.6.pdf

**Comment by tdiethe** [comment]
Further to this, I see there's an option to add nuget packages that aren't
source controlled (see
http://docs.nuget.org/docs/workflows/using-nuget-without-committing-packages),
but this seems to be a VS solution only. I'm not sure what will happen if I
add the nuget package, but then don't commit the binaries themselves - I'll
try that first (I'll open up a VM to test).

**Comment by tdiethe** [comment]
Ok that seemed to work. I just cloned in a Windows VM using VS, and it automatically downloaded the missing Nuget packages for me.

**Comment by oliparson** [comment]
Great. I'll close this request, and would you mind issuing a new one?

**Pull request closed without merging**
